# Generated by Django 2.1.3 on 2019-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_auto_20181115_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
