# Generated by Django 2.1.3 on 2019-02-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_auto_20190202_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Game',
        ),
    ]
