# Generated by Django 2.1.3 on 2019-02-09 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0007_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('cup', models.CharField(choices=[('GOLD', 0), ('SILVER', 1), ('BRONZE', 2), ('NONE', 3)], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AddField(
            model_name='game',
            name='times_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='DEFAULT_PIC', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Game'),
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Player'),
        ),
        migrations.AddField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Game'),
        ),
        migrations.AddField(
            model_name='rating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Player'),
        ),
    ]
