# Generated by Django 2.1.3 on 2019-02-09 15:18

from django.db import migrations, models
import django.db.models.deletion
import webshop.utils


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_auto_20190209_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', webshop.utils.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webshop.Player'),
        ),
    ]
